#! /bin/bash

update-alternatives --config idlj
update-alternatives --config idljappletviewer
update-alternatives --config ControlPanel
update-alternatives --config jar
update-alternatives --config extcheck
update-alternatives --config jarsigner
update-alternatives --config javafxpackager
update-alternatives --config javah
update-alternatives --config java
update-alternatives --config javac
update-alternatives --config javap
update-alternatives --config javapackager
update-alternatives --config java-rmi.cgi
update-alternatives --config javaws
update-alternatives --config jcmd
update-alternatives --config jconsole
update-alternatives --config jcontrol
update-alternatives --config jdb
update-alternatives --config jdeps
update-alternatives --config jhat
update-alternatives --config jinfo
update-alternatives --config jjs
update-alternatives --config jmap
update-alternatives --config jmc
update-alternatives --config jmc.ini
update-alternatives --config jps
update-alternatives --config jrunscript
update-alternatives --config jsadebugd
update-alternatives --config jstack
update-alternatives --config jstat
update-alternatives --config jstatd
update-alternatives --config jvisualvm
update-alternatives --config keytool
update-alternatives --config native2ascii
update-alternatives --config orbd
update-alternatives --config pack200
update-alternatives --config policytool
update-alternatives --config rmic
update-alternatives --config rmid
update-alternatives --config rmiregistry
update-alternatives --config schemagen
update-alternatives --config serialver
update-alternatives --config servertool
update-alternatives --config tnameserv
update-alternatives --config unpack200
update-alternatives --config wsgen
update-alternatives --config wsimport
update-alternatives --config xjs
