#! /bin/bash

update-alternatives --install /usr/bin/javah javah /opt/java/jdk1.8.0_92/bin/javah 100
update-alternatives --install /usr/bin/javap javap /opt/java/jdk1.8.0_92/bin/javap 100
update-alternatives --install /usr/bin/appletviewer appletviewer /opt/java/jdk1.8.0_92/bin/appletviewer 100
update-alternatives --install /usr/bin/extcheck extcheck /opt/java/jdk1.8.0_92/bin/extcheck 100
update-alternatives --install /usr/bin/idlj idlj /opt/java/jdk1.8.0_92/bin/idlj 100
update-alternatives --install /usr/bin/jar jar /opt/java/jdk1.8.0_92/bin/jar 100
update-alternatives --install /usr/bin/jarsigner jarsigner /opt/java/jdk1.8.0_92/bin/jarsigner 100
update-alternatives --install /usr/bin/javafxpackager javafxpackager /opt/java/jdk1.8.0_92/bin/javafxpackager 100
update-alternatives --install /usr/bin/javapackager javapackager /opt/java/jdk1.8.0_92/bin/javapackager 100
update-alternatives --install /usr/bin/javaws javaws /opt/java/jdk1.8.0_92/bin/javaws 100
update-alternatives --install /usr/bin/jcmd jcmd /opt/java/jdk1.8.0_92/bin/jcmd 100
update-alternatives --install /usr/bin/jconsole jconsole /opt/java/jdk1.8.0_92/bin/jconsole 100
update-alternatives --install /usr/bin/jcontrol jcontrol /opt/java/jdk1.8.0_92/bin/jcontrol 100
update-alternatives --install /usr/bin/jdb jdb /opt/java/jdk1.8.0_92/bin/jdb 100
update-alternatives --install /usr/bin/jdeps jdeps /opt/java/jdk1.8.0_92/bin/jdeps 100
update-alternatives --install /usr/bin/java-rmi.cgi java-rmi.cgi /opt/java/jdk1.8.0_92/bin/java-rmi.cgi 100
update-alternatives --install /usr/bin/jhat jhat /opt/java/jdk1.8.0_92/bin/jhat 100
update-alternatives --install /usr/bin/jinfo jinfo /opt/java/jdk1.8.0_92/bin/jinfo 100
update-alternatives --install /usr/bin/jjs jjs /opt/java/jdk1.8.0_92/bin/jjs 100
update-alternatives --install /usr/bin/jmap jmap /opt/java/jdk1.8.0_92/bin/jmap 100
update-alternatives --install /usr/bin/jmc jmc /opt/java/jdk1.8.0_92/bin/jmc 100
update-alternatives --install /usr/bin/jmc.ini jmc.ini /opt/java/jdk1.8.0_92/bin/jmc.ini 100
update-alternatives --install /usr/bin/jps jps /opt/java/jdk1.8.0_92/bin/jps 100
update-alternatives --install /usr/bin/jrunscript jrunscript /opt/java/jdk1.8.0_92/bin/jrunscript 100
update-alternatives --install /usr/bin/jsadebugd jsadebugd /opt/java/jdk1.8.0_92/bin/jsadebugd 100
update-alternatives --install /usr/bin/jstack jstack /opt/java/jdk1.8.0_92/bin/jstack 100
update-alternatives --install /usr/bin/jstatd jstatd /opt/java/jdk1.8.0_92/bin/jstatd 100
update-alternatives --install /usr/bin/jvisualvm jvisualvm /opt/java/jdk1.8.0_92/bin/jvisualvm 100
update-alternatives --install /usr/bin/keytool keytool /opt/java/jdk1.8.0_92/bin/keytool 100
update-alternatives --install /usr/bin/native2ascii native2ascii /opt/java/jdk1.8.0_92/bin/native2ascii 100
update-alternatives --install /usr/bin/orbd orbd /opt/java/jdk1.8.0_92/bin/orbd 100
update-alternatives --install /usr/bin/pack200 pack200 /opt/java/jdk1.8.0_92/bin/pack200 100
update-alternatives --install /usr/bin/policytool policytool /opt/java/jdk1.8.0_92/bin/policytool 100
update-alternatives --install /usr/bin/rmic rmic /opt/java/jdk1.8.0_92/bin/rmic 100
update-alternatives --install /usr/bin/rmid rmid /opt/java/jdk1.8.0_92/bin/rmid 100
update-alternatives --install /usr/bin/rmiregistry rmiregistry /opt/java/jdk1.8.0_92/bin/rmiregistry 100
update-alternatives --install /usr/bin/schemagen schemagen /opt/java/jdk1.8.0_92/bin/schemagen 100
update-alternatives --install /usr/bin/serialver serialver /opt/java/jdk1.8.0_92/bin/serialver 100
update-alternatives --install /usr/bin/servertool servertool /opt/java/jdk1.8.0_92/bin/servertool 100
update-alternatives --install /usr/bin/tnameserv tnameserv /opt/java/jdk1.8.0_92/bin/tnameserv 100
update-alternatives --install /usr/bin/unpack200 unpack200 /opt/java/jdk1.8.0_92/bin/unpack200 100
update-alternatives --install /usr/bin/wsgen wsgen /opt/java/jdk1.8.0_92/bin/wsgen 100
update-alternatives --install /usr/bin/wsimport wsimport /opt/java/jdk1.8.0_92/bin/wsimport 100
update-alternatives --install /usr/bin/xjc xjc /opt/java/jdk1.8.0_92/bin/xjc 100
update-alternatives --install /usr/bin/java java /opt/java/jdk1.8.0_92/bin/java 100
update-alternatives --install /usr/bin/javac javac /opt/java/jdk1.8.0_92/bin/javac 100
update-alternatives --install /usr/bin/javadoc javadoc /opt/java/jdk1.8.0_92/bin/javadoc 100
