# virtualenv and virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON=/var/mypython/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/var/mypython/bin/virtualenv
export WORKON_HOME=$HOME/.virtualenvs
source /var/mypython/bin/virtualenvwrapper.sh

if [ -f ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh ]; then
    source ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
fi



