export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH=/home/kitso/bin:/home/kitso/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/kitso/.rvm/bin:/home/kitso/.rvm/bin:/home/kitso/.rvm/bin:/bin

export GOROOT=/opt/go
export PATH=$PATH:$GOROOT/bin

# virtualenv and virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON=/home/kitso/.pyenv/versions/3.5.2/bin/python 
export VIRTUALENVWRAPPER_VIRTUALENV=/home/kitso/.pyenv/versions/3.5.2/bin/virtualenv
export WORKON_HOME=$HOME/.virtualenvs
source /home/kitso/.pyenv/versions/3.5.2/bin/virtualenvwrapper.sh

export PYTHONPATH=~/.pythonrc.py

man() {
	env \
		LESS_TERMCAP_mb=$(printf "\e[1;31m") \
		LESS_TERMCAP_md=$(printf "\e[1;31m") \
		LESS_TERMCAP_me=$(printf "\e[0m") \
		LESS_TERMCAP_se=$(printf "\e[0m") \
		LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
		LESS_TERMCAP_ue=$(printf "\e[0m") \
		LESS_TERMCAP_us=$(printf "\e[1;32m") \
			man "$@"
}

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(pyenv init -)"

# powerline stuff
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
if [ -f  /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh ]; then
    source /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh
fi
